// Generated by gir (https://github.com/gtk-rs/gir @ b4ad84f7c554)
// from  (@ cfa7ae33cb18+)
// from gir-files (@ baa82dc06419)
// DO NOT EDIT

fn main() {
    if std::env::var("DOCS_RS").is_ok() {
        // prevent linking libraries to avoid documentation failure
        return;
    }

    if let Err(s) = system_deps::Config::new().probe() {
        println!("cargo:warning={s}");
        std::process::exit(1);
    }
}
