include:
  - component: gitlab.gnome.org/GNOME/citemplates/release-service@master
    inputs:
      dist-job-name: "build-release-tarball"
      tarball-artifact-path: "${TARBALL_ARTIFACT_PATH}"

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_TAG

variables:
  # Clone test-images
  GIT_SUBMODULE_STRATEGY: recursive
  RUST_BACKTRACE: "full"
  TARBALL_ARTIFACT_PATH: "builddir/meson-dist/${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.tar.xz"

.cargo_bininstall:
  before_script:
    - curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

.install_dependencies:
  before_script:
    - |
      if [ -n "$CUSTOM_ARCH" ]; then
        dpkg --add-architecture $CUSTOM_ARCH
      fi
    - apt-get update
    - apt-get install -y git curl meson gcc pkg-config gi-docgen valac gobject-introspection python3-gi build-essential gettext clang mold bubblewrap
    - |
      if [ -n "$CUSTOM_ARCH" ]; then
        apt-get install -y gcc-multilib
      fi
    - apt-get install -y libc6-dev:$CUSTOM_ARCH libgirepository1.0-dev:$CUSTOM_ARCH libseccomp-dev:$CUSTOM_ARCH libfontconfig-dev:$CUSTOM_ARCH libgtk-4-dev:$CUSTOM_ARCH libcairo2-dev:$CUSTOM_ARCH librsvg2-dev:$CUSTOM_ARCH libjxl-dev:$CUSTOM_ARCH
    # We need libfheif 1.20
    - echo "deb http://deb.debian.org/debian forky main" > /etc/apt/sources.list.d/forky.list
    - apt-get update
    - apt-get install -y libheif-dev:$CUSTOM_ARCH libheif-plugin-aomenc:$CUSTOM_ARCH libheif-plugin-x265:$CUSTOM_ARCH

  artifacts:
    when: always
    paths:
      - tests/failures
      - builddir/meson-logs

build-release-tarball:
  stage: build
  image: rust:1.93-trixie
  extends: .install_dependencies
  script:
    - meson setup builddir
    - meson install -C builddir
    - apt-get install -y python3-tomlkit
    - ./build-aux/publish-crates-io.py
    - meson dist -C builddir
  artifacts:
    name: "${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}"
    when: always
    paths:
      - "${TARBALL_ARTIFACT_PATH}"
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_REF_PROTECTED

benchmark:
  image: quay.io/podman/stable:v5.8.2
  allow_failure: true
  variables:
    STORAGE_DRIVER: vfs
    IMAGE: registry.bencher.dev/glycin:latest
  before_script:
    - dnf install -y which
    - curl --proto '=https' --tlsv1.2 -sSfL https://bencher.dev/download/install-cli.sh | sh
    - source $HOME/.cargo/env
    - bencher --version
  script:
    - podman login -u sophieherold@gnome.org -p $BENCHER_TOKEN registry.bencher.dev
    - podman build -t $IMAGE -f build-aux/bencher/Dockerfile .
    - podman push $IMAGE

    - echo "Bencher output:" > bencher.txt
    - set -x
    - bencher run --quiet --format html --project glycin --branch "$CI_COMMIT_REF_NAME" --token $BENCHER_TOKEN --start-point "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" --image $IMAGE "./run-benchmarks.bash" >> bencher.txt
    - bencher run --quiet --format html --project glycin --branch "$CI_COMMIT_REF_NAME" --token $BENCHER_TOKEN --start-point "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" --image $IMAGE "./filesizes.py" >> bencher.txt
    - cat bencher.txt
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
      allow_failure: true
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

cargo-clippy:
  image: rust
  extends: .install_dependencies
  interruptible: true
  allow_failure: true
  script:
    - rustup component add clippy
    - meson setup -Dprofile=dev -Dglycin-loaders=false -Dglycin-thumbnailer=false --prefix=/usr builddir
    - meson install -C builddir
    - cargo clippy --no-deps -- --deny warnings

test-x86_64:
  image: rust:1.93-trixie
  extends: .install_dependencies
  interruptible: true
  script:
    # Skip isolated install for tests to test usual installation scenario
    - meson setup -Dprofile=dev -Dpython_tests=true -Dtest_skip_install=true -Dcapi_docs=true --prefix=/usr -Dloaders=glycin-heif,glycin-image-rs,glycin-jxl,glycin-raw,glycin-svg,glycin-test builddir
    - meson install -C builddir
    - meson test -vC builddir
    - mv builddir/libglycin/libglycin-2 libglycin-docs
    - mv builddir/libglycin/libglycin-gtk4-2 libglycin-gtk4-docs
  artifacts:
    paths:
      - libglycin-docs
      - libglycin-gtk4-docs

test-i686:
  variables:
    CUSTOM_ARCH: i386
  image: rust:1.93-trixie
  extends: .install_dependencies
  interruptible: true
  script:
    - rustup target add i686-unknown-linux-gnu
    - apt-get install -y ninja-build
    # Disable introspection/vapi because it segfaults in i686
    - meson setup --cross-file build-aux/cross/cross-linux-i686.txt -Dtest_skip_ext=avif -Dprofile=dev -Dintrospection=false -Dvapi=false -Dtest_skip_install=true --prefix=/usr -Dloaders=glycin-heif,glycin-image-rs,glycin-jxl,glycin-raw,glycin-svg,glycin-test builddir
    - meson install -C builddir
    # Disable tests for now since they fail with pkg-config error
    #- meson test -vC builddir

test-aarch64:
  image: rust:1.93-trixie
  tags:
    # Required since other configuration don't allow apt-get
    - asan-aarch64
  extends: .install_dependencies
  interruptible: true
  script:
    - export LD_LIBRARY_PATH=/usr/local/lib/aarch64-linux-gnu/
    - meson setup -Dprofile=dev -Dpython_tests=true -Dtest_skip_install=true --prefix=/usr -Dloaders=glycin-heif,glycin-image-rs,glycin-jxl,glycin-raw,glycin-svg,glycin-test builddir
    - meson install -C builddir
    - meson test -vC builddir

test-fedora43-loaders:
  image: 'registry.fedoraproject.org/fedora:43'
  interruptible: true
  script:
    - dnf install --assumeyes glycin-loaders cargo glib2-devel gtk4-devel libseccomp-devel fontconfig-devel
    - rm tests/test-images/images/animated-numbers/animated-numbers.avif
    - rm tests/test-images/images/animated-numbers/animated-numbers.heic
    - rm tests/test-images/editing/crop/crop_ycck.jpg
    - rm tests/test-images/editing/crop-grayscale/crop-grayscale.jpg
    - rm tests/test-images/images/color/color.hdr
    - rm tests/test-images/images/color/color.jp2
    - rm tests/test-images/images/color/color.xpm
    - rm tests/test-images/images/monochrome/monochrome.xbm
    - rm tests/test-images/images/color-variations/color-variations-u32.exr
    - GLYCIN_TEST_SKIP_EXT=heic cargo test -p tests -- --nocapture --skip processor_creator_supported_memory_formats --test-threads 1 processor_

test-fedora44-loaders:
  image: 'registry.fedoraproject.org/fedora:44'
  interruptible: true
  script:
    - dnf install --assumeyes glycin-loaders cargo glib2-devel gtk4-devel libseccomp-devel fontconfig-devel
    - rm tests/test-images/images/animated-numbers/animated-numbers.avif
    - rm tests/test-images/images/animated-numbers/animated-numbers.heic
    - rm tests/test-images/images/color/color.hdr
    - rm tests/test-images/images/color-variations/color-variations-u32.exr
    - GLYCIN_TEST_SKIP_EXT=heic cargo test -p tests -- --nocapture --skip processor_creator_supported_memory_formats --test-threads 1 processor_

macos:
  tags:
    - macos
    - arm64
  cache:
    - key: $CI_JOB_NAME_SLUG
      paths:
        - ccache
  variables:
    CCACHE_MAXSIZE: "250Mi"
    CCACHE_DIR: $CI_PROJECT_DIR/ccache
    ORKA_RUNNER: sonoma-5
    PKG_CONFIG_PATH: $CI_PROJECT_DIR/.venv/lib/pkgconfig
    SDKROOT: /opt/sdks/MacOSX11.3.sdk
  before_script:
    - | # Setup the virtual environment with basic set of tools.
      python3 -m venv .venv
      source .venv/bin/activate
      pip3 install meson==1.9.0 ninja==1.11.1.1 cmake
      ln -s /opt/ccache/ccache .venv/bin
      ln -s /opt/rustup/toolchains/1.93.1-aarch64-apple-darwin/bin/* .venv/bin
    - | # Clone GTK early so we can access wrapped GLib version.
      git clone https://gitlab.gnome.org/gnome/gtk.git
      git -C gtk checkout main # Use main for now, since all others are broken due to pango/glib version missmatch
      git -C gtk submodule update --init --recursive
    - | # Build GLib.
      pip3 install crudini==0.9.6   # to pick the version from wrap file
      pip3 install packaging==24.2  # required by GLib
      git clone --depth 1 --branch $(crudini --get gtk/subprojects/glib.wrap wrap-git revision) https://gitlab.gnome.org/gnome/glib.git
      meson setup -Dprefix=${CI_PROJECT_DIR}/.venv -Dintrospection=disabled -Dtests=false glib.build glib
      meson compile -C glib.build
      meson install -C glib.build
    - | # Build GTK.
      meson setup -Dprefix=${CI_PROJECT_DIR}/.venv \
          -Dmedia-gstreamer=disabled \
          -Dintrospection=disabled \
          -Dbuild-demos=false \
          -Dbuild-examples=false \
          -Dbuild-testsuite=false \
          -Dbuild-tests=false \
          -Dvulkan=disabled \
          gtk.build gtk
      meson compile -C gtk.build
      meson install -C gtk.build
    - | # Install pkgconfig.
      curl -L $CI_API_V4_URL/projects/30437/packages/generic/pkgconfig/v0.29.2+10/pkg-config-0.29.2+10_$(uname -m).tar.xz | tar -C .venv -xJ
  script:
    - cargo build -p glycin --features gdk4
    - meson setup -Dintrospection=false -Dvapi=false builddir
    - meson compile -C builddir

windows-gnu:
  image: 'registry.fedoraproject.org/fedora:44'
  interruptible: true
  script:
    - dnf install -y gcc mingw64-gtk4 x86_64-w64-mingw32-gcc
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - export PATH="/root/.cargo/bin:${PATH}"
    - rustup target add x86_64-pc-windows-gnu
    - export PKG_CONFIG_ALLOW_CROSS=1
    - export PKG_CONFIG_PATH_x86_64_pc_windows_gnu=/usr/x86_64-w64-mingw32/sys-root/mingw/lib/pkgconfig/
    - cargo build -p glycin --features gdk4 --target x86_64-pc-windows-gnu
    # Tests
    - dnf install -y wine-core wine-desktop
    - export CARGO_TARGET_X86_64_PC_WINDOWS_GNU_RUNNER=wine
    - export WINEPATH="Z:\\usr\\x86_64-w64-mingw32\\sys-root\\mingw\\bin"
    - GLYCIN_TEST_SKIP_EXT=svg,svgz,avif,heic,jxl cargo test -p tests --no-default-features --features async-io,builtin-loaders --target x86_64-pc-windows-gnu
    # Build libglycin
    - dnf install -y meson
    - meson setup --cross-file build-aux/cross/cross-windows.txt -Dintrospection=false -Dvapi=false -Dglycin-thumbnailer=false -Dlibglycin-gtk4=false -Dprofile=dev builddir
    - meson compile -vvvC builddir

cargo-semver-checks:
  image: rust
  extends: .install_dependencies
  interruptible: true
  variables:
    GIT_DEPTH: 1000
  script:
    # We need libglycin to be properly installed for pkgconf to work in libglycin-gtk4
    - meson setup -Dprofile=dev -Dglycin-loaders=false -Dglycin-thumbnailer=false --prefix=/usr builddir
    - meson install -C builddir
    - cargo install cargo-semver-checks --locked
    - cargo semver-checks --only-explicit-features --features async-io -p glycin
    - cargo semver-checks --only-explicit-features --features tokio -p glycin
    - cargo semver-checks --only-explicit-features --features async-io -p glycin-utils
    - cargo semver-checks --only-explicit-features --features tokio -p glycin-utils
    # Use the commit where we changed to defining all functions as unsafe
    - cargo semver-checks -p libglycin -p libglycin-gtk4 --baseline-rev 97b80be3

libglycin-rebind:
  image: rust:1.93-trixie
  extends: .install_dependencies
  interruptible: true
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    RUSTDOCFLAGS: "--cfg docsrs"
  script:
    - git submodule update --checkout
    - meson setup -Dprofile=dev -Dglycin-loaders=false -Dglycin-thumbnailer=false -Dtest_skip_install=true -Dvapi=false --prefix=/usr builddir
    - meson install -C builddir
    - cargo build --package libglycin-gtk4-rebind --package libglycin-rebind
    # dependencies for the docs
    - curl --proto '=https' --tlsv1.2 -sSf -o libglycin-rebind/gir-rustdoc.py
      https://gitlab.gnome.org/World/Rust/gir-rustdoc/-/raw/main/gir-rustdoc.py
    - apt update
    - apt install -y python3-requests
    # generate the docs
    - cd libglycin-rebind
    - cargo install rustdoc-stripper
    - ./gir/generator.py --embed-docs --no-fmt
    - rustup default nightly
    - eval $(./gir-rustdoc.py --branch=main pre-docs)
    - cd ../  # move back to the root
    - cargo doc --all-features --no-deps -p libglycin-gtk4-rebind -p libglycin-rebind -p libglycin-gtk4-rebind-sys -p libglycin-rebind-sys
    - mkdir public
    - mv target/doc public/rust
  artifacts:
    paths:
      - public

cargo-fmt:
  image: rust
  interruptible: true
  script:
    - rustup component add rustfmt
    - cargo fmt --check

cargo-deny:
  image: rust
  interruptible: true
  script:
    - cargo install cargo-deny --locked
    - cargo deny --target x86_64-unknown-linux-gnu check

cargo-vet:
  image: "rust"
  allow_failure: true
  interruptible: true
  script:
    - cargo install cargo-vet
    - CARGO_BUILD_TARGET=x86_64-unknown-linux-gnu cargo vet || true

website:
  image: rust
  extends: .install_dependencies
  interruptible: true
  script:
    - ./docs/website/build.bash
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  dependencies:
    - website
    - test-x86_64
  script:
    - mv libglycin-docs public/libglycin
    - mv libglycin-gtk4-docs public/libglycin-gtk4
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
