[loader:image/jxl]
Exec = @EXEC@
Identifiers=0:\\xFF\\x0A;0:\\x00\\x00\\x00\\x0CJXL\\x20\\x0D\\x0A\\x87\\x0A;
Extension=jxl

[editor:image/jxl]
Exec = @EXEC@
Creator = true
CreatorEncodingQuality = true
CreatorMemoryFormats=R8g8b8
