// Generated by gir (https://github.com/gtk-rs/gir @ b4ad84f7c554)
// from  (@ cfa7ae33cb18+)
// from gir-files (@ baa82dc06419)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "GlyCicp", sizeof(GlyCicp), alignof(GlyCicp));
    printf("%s;%zu;%zu\n", "GlyColorMode", sizeof(GlyColorMode), alignof(GlyColorMode));
    printf("%s;%zu;%zu\n", "GlyCreatorClass", sizeof(GlyCreatorClass), alignof(GlyCreatorClass));
    printf("%s;%zu;%zu\n", "GlyEncodedImageClass", sizeof(GlyEncodedImageClass), alignof(GlyEncodedImageClass));
    printf("%s;%zu;%zu\n", "GlyFrameClass", sizeof(GlyFrameClass), alignof(GlyFrameClass));
    printf("%s;%zu;%zu\n", "GlyFrameDetailsClass", sizeof(GlyFrameDetailsClass), alignof(GlyFrameDetailsClass));
    printf("%s;%zu;%zu\n", "GlyFrameRequestClass", sizeof(GlyFrameRequestClass), alignof(GlyFrameRequestClass));
    printf("%s;%zu;%zu\n", "GlyImageClass", sizeof(GlyImageClass), alignof(GlyImageClass));
    printf("%s;%zu;%zu\n", "GlyLoaderClass", sizeof(GlyLoaderClass), alignof(GlyLoaderClass));
    printf("%s;%zu;%zu\n", "GlyLoaderError", sizeof(GlyLoaderError), alignof(GlyLoaderError));
    printf("%s;%zu;%zu\n", "GlyMemoryFormat", sizeof(GlyMemoryFormat), alignof(GlyMemoryFormat));
    printf("%s;%zu;%zu\n", "GlyMemoryFormatSelection", sizeof(GlyMemoryFormatSelection), alignof(GlyMemoryFormatSelection));
    printf("%s;%zu;%zu\n", "GlyNewFrameClass", sizeof(GlyNewFrameClass), alignof(GlyNewFrameClass));
    printf("%s;%zu;%zu\n", "GlyPhysicalDimensionUnit", sizeof(GlyPhysicalDimensionUnit), alignof(GlyPhysicalDimensionUnit));
    printf("%s;%zu;%zu\n", "GlyPixelDensityClass", sizeof(GlyPixelDensityClass), alignof(GlyPixelDensityClass));
    printf("%s;%zu;%zu\n", "GlySandboxSelector", sizeof(GlySandboxSelector), alignof(GlySandboxSelector));
    return 0;
}
