[loader:image/avif]
Exec = @EXEC@
Identifiers=4:ftypavif;
Extension=avif

[editor:image/avif]
Exec = @EXEC@
Creator = true
CreatorColorIccProfile = true
CreatorEncodingQuality = true
CreatorMemoryFormats=R8g8b8;R8g8b8a8

[loader:image/heif]
Exec = @EXEC@
Identifiers=4:ftypheic;
Extension=avif

[editor:image/heif]
Exec = @EXEC@
Creator = true
CreatorColorIccProfile = true
CreatorEncodingQuality = true
CreatorMemoryFormats=R8g8b8;R8g8b8a8
